
applications:

  - name: guestbook
    project: default
    source:
      repoURL: https://cloudnativeapp.github.io/charts/curated/
      chart: guestbook
      targetRevision: 0.2.0
      plugin:
        name: helm-overdrive
        env:
          - name: git-repo
            value: https://github.com/Energinet-DataHub/eo-base-environment
          - name: git-rev
            value: main
          - name: base-config
            value: base/applications/guestbook/guestbook_values.yaml
          - name: base-extra
            value: base/applications/guestbook/extra
          - name: base-globals-yaml
            value: base/global.yaml

          - name: env-config
            value: env/{{ .Values.env }}/applications/guestbook/guestbook_values.yaml
          - name: env-extra
            value: env/{{ .Values.env }}/applications/guestbook/extra
          - name: env-globals-yaml
            value: env/{{ .Values.env }}/global.yaml
